import type { Database } from '../types/index.js'
import fs from 'fs'
import path from 'path'

export const SAMPLE_EVIDENCE_FILENAME = 'sample_anomaly_001.png'
const PNG_1X1_BLUE_BASE64 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z/C/HgAGgwJ/lK3Q6wAAAABJRU5ErkJggg=='

export function createSampleEvidenceFiles(evidenceDir: string): void {
  const filePath = path.join(evidenceDir, SAMPLE_EVIDENCE_FILENAME)
  if (!fs.existsSync(filePath)) {
    const buffer = Buffer.from(PNG_1X1_BLUE_BASE64, 'base64')
    fs.writeFileSync(filePath, buffer)
  }
}

function daysAgo(n: number): string {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d.toISOString().slice(0, 10)
}

function tsAgo(ms: number): string {
  return new Date(Date.now() - ms).toISOString()
}

export function getInitialData(): Database {
  const now = new Date().toISOString()

  return {
    devices: [
      {
        id: 'DEV_001',
        name: 'CNC加工中心 A-1',
        code: 'CNC-A1',
        location: '一号车间 3号位',
        description: '五轴联动数控加工中心',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'DEV_002',
        name: '注塑机 B-2',
        code: 'INJ-B2',
        location: '二号车间 1号位',
        description: '320吨伺服注塑机',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'DEV_003',
        name: '冲压机 C-3',
        code: 'PRS-C3',
        location: '一号车间 7号位',
        description: '400吨高速冲床',
        createdAt: now,
        updatedAt: now,
      },
    ],
    shifts: [
      {
        id: 'SHFT_001',
        name: '早班',
        type: 'MORNING',
        startTime: '08:00',
        endTime: '16:00',
        description: '白班第一班',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'SHFT_002',
        name: '中班',
        type: 'AFTERNOON',
        startTime: '16:00',
        endTime: '00:00',
        description: '白班第二班',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'SHFT_003',
        name: '夜班',
        type: 'NIGHT',
        startTime: '00:00',
        endTime: '08:00',
        description: '夜班',
        createdAt: now,
        updatedAt: now,
      },
    ],
    checkItems: [
      {
        id: 'CI_001',
        name: '设备外观检查',
        code: 'VIS-001',
        category: '目视检查',
        description: '检查设备外观是否完好，无破损、无变形',
        standard: '设备外观整洁，无明显磕碰、变形、锈蚀',
        deviceIds: ['DEV_001', 'DEV_002', 'DEV_003'],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'CI_002',
        name: '润滑油位',
        code: 'OIL-001',
        category: '润滑系统',
        description: '检查各润滑点油位是否正常',
        standard: '油位在上下刻度线之间，无渗漏',
        deviceIds: ['DEV_001', 'DEV_002', 'DEV_003'],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'CI_003',
        name: '气压系统',
        code: 'AIR-001',
        category: '气动系统',
        description: '检查气源压力和管路',
        standard: '气压 0.5~0.7MPa，管路无泄漏',
        deviceIds: ['DEV_001', 'DEV_002'],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'CI_004',
        name: '安全门开关',
        code: 'SAF-001',
        category: '安全装置',
        description: '检查安全门联锁功能',
        standard: '安全门打开时设备立即停止运行',
        deviceIds: ['DEV_001', 'DEV_002', 'DEV_003'],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'CI_005',
        name: '冷却系统',
        code: 'CLN-001',
        category: '温控系统',
        description: '检查冷却液循环和温度',
        standard: '冷却液充足，温度 20~28°C',
        deviceIds: ['DEV_001'],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'CI_006',
        name: '模具安装',
        code: 'MOL-001',
        category: '工装模具',
        description: '检查模具安装固定情况',
        standard: '模具安装牢固，定位准确',
        deviceIds: ['DEV_002', 'DEV_003'],
        createdAt: now,
        updatedAt: now,
      },
    ],
    inspectionPlans: [
      {
        id: 'PLAN_001',
        name: 'CNC-A1 日常点检',
        deviceId: 'DEV_001',
        shiftId: 'SHFT_001',
        checkItemIds: ['CI_001', 'CI_002', 'CI_003', 'CI_004', 'CI_005'],
        frequency: '每日每班次',
        description: 'CNC加工中心A-1每班开机前点检',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'PLAN_002',
        name: 'INJ-B2 日常点检',
        deviceId: 'DEV_002',
        shiftId: 'SHFT_001',
        checkItemIds: ['CI_001', 'CI_002', 'CI_003', 'CI_004', 'CI_006'],
        frequency: '每日每班次',
        description: '注塑机B-2每班开机前点检',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'PLAN_003',
        name: 'PRS-C3 日常点检',
        deviceId: 'DEV_003',
        shiftId: 'SHFT_002',
        checkItemIds: ['CI_001', 'CI_002', 'CI_004', 'CI_006'],
        frequency: '每日每班次',
        description: '冲压机C-3每班开机前点检',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'PLAN_004',
        name: 'INJ-B2 中班点检',
        deviceId: 'DEV_002',
        shiftId: 'SHFT_002',
        checkItemIds: ['CI_001', 'CI_002', 'CI_003', 'CI_004', 'CI_006'],
        frequency: '每日每班次',
        description: '注塑机B-2中班点检',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'PLAN_005',
        name: 'CNC-A1 夜班点检',
        deviceId: 'DEV_001',
        shiftId: 'SHFT_003',
        checkItemIds: ['CI_001', 'CI_002', 'CI_003', 'CI_004', 'CI_005'],
        frequency: '每日每班次',
        description: 'CNC加工中心A-1夜班点检',
        createdAt: now,
        updatedAt: now,
      },
    ],
    inspectionOrders: [
      {
        id: 'ORD_SAMPLE_001',
        planId: 'PLAN_001',
        deviceId: 'DEV_001',
        shiftId: 'SHFT_001',
        shiftDate: daysAgo(1),
        status: 'CLOSED',
        operator: '张工',
        supervisor: '李主管',
        results: [
          { id: 'R_001', checkItemId: 'CI_001', status: 'NORMAL', checkedAt: tsAgo(90000000), checkedBy: '张工' },
          { id: 'R_002', checkItemId: 'CI_002', status: 'NORMAL', checkedAt: tsAgo(89000000), checkedBy: '张工' },
          { id: 'R_003', checkItemId: 'CI_003', status: 'NORMAL', checkedAt: tsAgo(88000000), checkedBy: '张工' },
          { id: 'R_003b', checkItemId: 'CI_004', status: 'NORMAL', checkedAt: tsAgo(87000000), checkedBy: '张工' },
          { id: 'R_003c', checkItemId: 'CI_005', status: 'NORMAL', checkedAt: tsAgo(86000000), checkedBy: '张工' },
        ],
        anomalies: [],
        operationLogs: [
          { id: 'LOG_001', inspectionOrderId: 'ORD_SAMPLE_001', action: 'CREATE', fromStatus: null, toStatus: 'DRAFT', operator: '张工', timestamp: tsAgo(100000000) },
          { id: 'LOG_002', inspectionOrderId: 'ORD_SAMPLE_001', action: 'SUBMIT', fromStatus: 'DRAFT', toStatus: 'COMPLETED', operator: '张工', timestamp: tsAgo(80000000) },
          { id: 'LOG_002b', inspectionOrderId: 'ORD_SAMPLE_001', action: 'REVIEW', fromStatus: 'COMPLETED', toStatus: 'REVIEWED', operator: '李主管', timestamp: tsAgo(50000000) },
          { id: 'LOG_003', inspectionOrderId: 'ORD_SAMPLE_001', action: 'CLOSE', fromStatus: 'REVIEWED', toStatus: 'CLOSED', operator: '李主管', timestamp: tsAgo(40000000) },
        ],
        startedAt: tsAgo(100000000),
        submittedAt: tsAgo(80000000),
        reviewedAt: tsAgo(50000000),
        closedAt: tsAgo(40000000),
        createdAt: tsAgo(100000000),
        updatedAt: tsAgo(40000000),
      },
      {
        id: 'ORD_SAMPLE_002',
        planId: 'PLAN_002',
        deviceId: 'DEV_002',
        shiftId: 'SHFT_001',
        shiftDate: daysAgo(0),
        status: 'PENDING_REVIEW',
        operator: '王工',
        results: [
          { id: 'R_004', checkItemId: 'CI_001', status: 'NORMAL', checkedAt: tsAgo(600000), checkedBy: '王工' },
          { id: 'R_005', checkItemId: 'CI_002', status: 'ANOMALY', anomalyId: 'ANOM_001', remark: '润滑油位偏低', checkedAt: tsAgo(500000), checkedBy: '王工' },
        ],
        anomalies: [
          {
            id: 'ANOM_001',
            inspectionOrderId: 'ORD_SAMPLE_002',
            checkItemId: 'CI_002',
            description: '润滑油位低于最低刻度线约2cm，暂未发现渗漏点',
            severity: 'MEDIUM',
            evidencePaths: [`/api/evidence/${SAMPLE_EVIDENCE_FILENAME}`],
            reportedBy: '王工',
            reportedAt: tsAgo(500000),
          },
        ],
        operationLogs: [
          { id: 'LOG_004', inspectionOrderId: 'ORD_SAMPLE_002', action: 'CREATE', fromStatus: null, toStatus: 'DRAFT', operator: '王工', timestamp: tsAgo(1200000) },
          { id: 'LOG_005', inspectionOrderId: 'ORD_SAMPLE_002', action: 'SUBMIT_WITH_ANOMALY', fromStatus: 'DRAFT', toStatus: 'PENDING_REVIEW', operator: '王工', timestamp: tsAgo(400000) },
        ],
        startedAt: tsAgo(1200000),
        submittedAt: tsAgo(400000),
        createdAt: tsAgo(1200000),
        updatedAt: tsAgo(400000),
      },
      {
        id: 'ORD_SAMPLE_003',
        planId: 'PLAN_003',
        deviceId: 'DEV_003',
        shiftId: 'SHFT_002',
        shiftDate: daysAgo(2),
        status: 'CLOSED',
        operator: '赵工',
        supervisor: '李主管',
        results: [
          { id: 'R_006', checkItemId: 'CI_001', status: 'NORMAL', checkedAt: tsAgo(200000000), checkedBy: '赵工' },
          { id: 'R_007', checkItemId: 'CI_002', status: 'ANOMALY', anomalyId: 'ANOM_002', checkedAt: tsAgo(199000000), checkedBy: '赵工' },
          { id: 'R_008', checkItemId: 'CI_004', status: 'NORMAL', checkedAt: tsAgo(198000000), checkedBy: '赵工' },
          { id: 'R_009', checkItemId: 'CI_006', status: 'NORMAL', checkedAt: tsAgo(197000000), checkedBy: '赵工' },
        ],
        anomalies: [
          {
            id: 'ANOM_002',
            inspectionOrderId: 'ORD_SAMPLE_003',
            checkItemId: 'CI_002',
            description: '润滑油有轻微渗漏痕迹',
            severity: 'LOW',
            evidencePaths: [`/api/evidence/${SAMPLE_EVIDENCE_FILENAME}`],
            reportedBy: '赵工',
            reportedAt: tsAgo(199000000),
            resolvedAt: tsAgo(150000000),
            resolvedBy: '李主管',
            resolution: '已紧固接头，观察中',
          },
        ],
        operationLogs: [
          { id: 'LOG_006', inspectionOrderId: 'ORD_SAMPLE_003', action: 'CREATE', fromStatus: null, toStatus: 'DRAFT', operator: '赵工', timestamp: tsAgo(210000000) },
          { id: 'LOG_007', inspectionOrderId: 'ORD_SAMPLE_003', action: 'SUBMIT_WITH_ANOMALY', fromStatus: 'DRAFT', toStatus: 'PENDING_REVIEW', operator: '赵工', timestamp: tsAgo(196000000) },
          { id: 'LOG_008', inspectionOrderId: 'ORD_SAMPLE_003', action: 'REVIEW', fromStatus: 'PENDING_REVIEW', toStatus: 'REVIEWED', operator: '李主管', timestamp: tsAgo(155000000) },
          { id: 'LOG_009', inspectionOrderId: 'ORD_SAMPLE_003', action: 'CLOSE', fromStatus: 'REVIEWED', toStatus: 'CLOSED', operator: '李主管', timestamp: tsAgo(150000000) },
        ],
        startedAt: tsAgo(210000000),
        submittedAt: tsAgo(196000000),
        reviewedAt: tsAgo(155000000),
        closedAt: tsAgo(150000000),
        createdAt: tsAgo(210000000),
        updatedAt: tsAgo(150000000),
      },
      {
        id: 'ORD_SAMPLE_004',
        planId: 'PLAN_004',
        deviceId: 'DEV_002',
        shiftId: 'SHFT_002',
        shiftDate: daysAgo(3),
        status: 'CLOSED',
        operator: '王工',
        supervisor: '李主管',
        results: [
          { id: 'R_010', checkItemId: 'CI_001', status: 'NORMAL', checkedAt: tsAgo(300000000), checkedBy: '王工' },
          { id: 'R_011', checkItemId: 'CI_002', status: 'ANOMALY', anomalyId: 'ANOM_003', checkedAt: tsAgo(299000000), checkedBy: '王工' },
          { id: 'R_012', checkItemId: 'CI_003', status: 'ANOMALY', anomalyId: 'ANOM_004', checkedAt: tsAgo(298000000), checkedBy: '王工' },
          { id: 'R_013', checkItemId: 'CI_004', status: 'NORMAL', checkedAt: tsAgo(297000000), checkedBy: '王工' },
          { id: 'R_014', checkItemId: 'CI_006', status: 'NORMAL', checkedAt: tsAgo(296000000), checkedBy: '王工' },
        ],
        anomalies: [
          {
            id: 'ANOM_003',
            inspectionOrderId: 'ORD_SAMPLE_004',
            checkItemId: 'CI_002',
            description: '润滑油严重不足，有明显泄漏',
            severity: 'HIGH',
            evidencePaths: [`/api/evidence/${SAMPLE_EVIDENCE_FILENAME}`],
            reportedBy: '王工',
            reportedAt: tsAgo(299000000),
            resolvedAt: tsAgo(250000000),
            resolvedBy: '李主管',
            resolution: '已停机维修，更换密封件',
          },
          {
            id: 'ANOM_004',
            inspectionOrderId: 'ORD_SAMPLE_004',
            checkItemId: 'CI_003',
            description: '气压不足，只有0.35MPa',
            severity: 'MEDIUM',
            evidencePaths: [`/api/evidence/${SAMPLE_EVIDENCE_FILENAME}`],
            reportedBy: '王工',
            reportedAt: tsAgo(298000000),
            resolvedAt: tsAgo(250000000),
            resolvedBy: '李主管',
            resolution: '已检查气泵，恢复正常',
          },
        ],
        operationLogs: [
          { id: 'LOG_010', inspectionOrderId: 'ORD_SAMPLE_004', action: 'CREATE', fromStatus: null, toStatus: 'DRAFT', operator: '王工', timestamp: tsAgo(310000000) },
          { id: 'LOG_011', inspectionOrderId: 'ORD_SAMPLE_004', action: 'SUBMIT_WITH_ANOMALY', fromStatus: 'DRAFT', toStatus: 'PENDING_REVIEW', operator: '王工', timestamp: tsAgo(295000000) },
          { id: 'LOG_012', inspectionOrderId: 'ORD_SAMPLE_004', action: 'REVIEW', fromStatus: 'PENDING_REVIEW', toStatus: 'REVIEWED', operator: '李主管', timestamp: tsAgo(260000000) },
          { id: 'LOG_013', inspectionOrderId: 'ORD_SAMPLE_004', action: 'CLOSE', fromStatus: 'REVIEWED', toStatus: 'CLOSED', operator: '李主管', timestamp: tsAgo(250000000) },
        ],
        startedAt: tsAgo(310000000),
        submittedAt: tsAgo(295000000),
        reviewedAt: tsAgo(260000000),
        closedAt: tsAgo(250000000),
        createdAt: tsAgo(310000000),
        updatedAt: tsAgo(250000000),
      },
      {
        id: 'ORD_SAMPLE_005',
        planId: 'PLAN_001',
        deviceId: 'DEV_001',
        shiftId: 'SHFT_001',
        shiftDate: daysAgo(5),
        status: 'CLOSED',
        operator: '张工',
        supervisor: '李主管',
        results: [
          { id: 'R_015', checkItemId: 'CI_001', status: 'NORMAL', checkedAt: tsAgo(450000000), checkedBy: '张工' },
          { id: 'R_016', checkItemId: 'CI_002', status: 'NORMAL', checkedAt: tsAgo(449000000), checkedBy: '张工' },
          { id: 'R_017', checkItemId: 'CI_003', status: 'NORMAL', checkedAt: tsAgo(448000000), checkedBy: '张工' },
          { id: 'R_018', checkItemId: 'CI_004', status: 'NORMAL', checkedAt: tsAgo(447000000), checkedBy: '张工' },
          { id: 'R_019', checkItemId: 'CI_005', status: 'ANOMALY', anomalyId: 'ANOM_005', checkedAt: tsAgo(446000000), checkedBy: '张工' },
        ],
        anomalies: [
          {
            id: 'ANOM_005',
            inspectionOrderId: 'ORD_SAMPLE_005',
            checkItemId: 'CI_005',
            description: '冷却液温度偏高，达到31°C',
            severity: 'MEDIUM',
            evidencePaths: [`/api/evidence/${SAMPLE_EVIDENCE_FILENAME}`],
            reportedBy: '张工',
            reportedAt: tsAgo(446000000),
            resolvedAt: tsAgo(420000000),
            resolvedBy: '李主管',
            resolution: '清理散热器，温度恢复正常',
          },
        ],
        operationLogs: [
          { id: 'LOG_014', inspectionOrderId: 'ORD_SAMPLE_005', action: 'CREATE', fromStatus: null, toStatus: 'DRAFT', operator: '张工', timestamp: tsAgo(460000000) },
          { id: 'LOG_015', inspectionOrderId: 'ORD_SAMPLE_005', action: 'SUBMIT_WITH_ANOMALY', fromStatus: 'DRAFT', toStatus: 'PENDING_REVIEW', operator: '张工', timestamp: tsAgo(445000000) },
          { id: 'LOG_016', inspectionOrderId: 'ORD_SAMPLE_005', action: 'REVIEW', fromStatus: 'PENDING_REVIEW', toStatus: 'REVIEWED', operator: '李主管', timestamp: tsAgo(425000000) },
          { id: 'LOG_017', inspectionOrderId: 'ORD_SAMPLE_005', action: 'CLOSE', fromStatus: 'REVIEWED', toStatus: 'CLOSED', operator: '李主管', timestamp: tsAgo(420000000) },
        ],
        startedAt: tsAgo(460000000),
        submittedAt: tsAgo(445000000),
        reviewedAt: tsAgo(425000000),
        closedAt: tsAgo(420000000),
        createdAt: tsAgo(460000000),
        updatedAt: tsAgo(420000000),
      },
      {
        id: 'ORD_SAMPLE_006',
        planId: 'PLAN_005',
        deviceId: 'DEV_001',
        shiftId: 'SHFT_003',
        shiftDate: daysAgo(7),
        status: 'COMPLETED',
        operator: '赵工',
        results: [
          { id: 'R_020', checkItemId: 'CI_001', status: 'NORMAL', checkedAt: tsAgo(650000000), checkedBy: '赵工' },
          { id: 'R_021', checkItemId: 'CI_002', status: 'NORMAL', checkedAt: tsAgo(649000000), checkedBy: '赵工' },
          { id: 'R_022', checkItemId: 'CI_003', status: 'NORMAL', checkedAt: tsAgo(648000000), checkedBy: '赵工' },
          { id: 'R_023', checkItemId: 'CI_004', status: 'NORMAL', checkedAt: tsAgo(647000000), checkedBy: '赵工' },
          { id: 'R_024', checkItemId: 'CI_005', status: 'NORMAL', checkedAt: tsAgo(646000000), checkedBy: '赵工' },
        ],
        anomalies: [],
        operationLogs: [
          { id: 'LOG_018', inspectionOrderId: 'ORD_SAMPLE_006', action: 'CREATE', fromStatus: null, toStatus: 'DRAFT', operator: '赵工', timestamp: tsAgo(660000000) },
          { id: 'LOG_019', inspectionOrderId: 'ORD_SAMPLE_006', action: 'SUBMIT', fromStatus: 'DRAFT', toStatus: 'COMPLETED', operator: '赵工', timestamp: tsAgo(645000000) },
        ],
        startedAt: tsAgo(660000000),
        submittedAt: tsAgo(645000000),
        createdAt: tsAgo(660000000),
        updatedAt: tsAgo(645000000),
      },
      {
        id: 'ORD_SAMPLE_007',
        planId: 'PLAN_003',
        deviceId: 'DEV_003',
        shiftId: 'SHFT_002',
        shiftDate: daysAgo(10),
        status: 'COMPLETED',
        operator: '张工',
        supervisor: '李主管',
        results: [
          { id: 'R_019', checkItemId: 'CI_001', status: 'NORMAL', checkedAt: tsAgo(890000000), checkedBy: '张工' },
          { id: 'R_020', checkItemId: 'CI_002', status: 'NORMAL', checkedAt: tsAgo(889000000), checkedBy: '张工' },
          { id: 'R_021', checkItemId: 'CI_004', status: 'NORMAL', checkedAt: tsAgo(888000000), checkedBy: '张工' },
          { id: 'R_022', checkItemId: 'CI_006', status: 'NORMAL', checkedAt: tsAgo(887000000), checkedBy: '张工' },
        ],
        anomalies: [],
        operationLogs: [
          { id: 'LOG_020', inspectionOrderId: 'ORD_SAMPLE_007', action: 'CREATE', fromStatus: null, toStatus: 'DRAFT', operator: '张工', timestamp: tsAgo(900000000) },
          { id: 'LOG_020b', inspectionOrderId: 'ORD_SAMPLE_007', action: 'SUBMIT', fromStatus: 'DRAFT', toStatus: 'COMPLETED', operator: '张工', timestamp: tsAgo(885000000) },
        ],
        startedAt: tsAgo(900000000),
        submittedAt: tsAgo(885000000),
        createdAt: tsAgo(900000000),
        updatedAt: tsAgo(885000000),
      },
      {
        id: 'ORD_SAMPLE_008',
        planId: 'PLAN_002',
        deviceId: 'DEV_002',
        shiftId: 'SHFT_001',
        shiftDate: daysAgo(15),
        status: 'CLOSED',
        operator: '张工',
        supervisor: '李主管',
        results: [
          { id: 'R_025', checkItemId: 'CI_001', status: 'NORMAL', checkedAt: tsAgo(1300000000), checkedBy: '张工' },
          { id: 'R_026', checkItemId: 'CI_002', status: 'NORMAL', checkedAt: tsAgo(1299000000), checkedBy: '张工' },
          { id: 'R_027', checkItemId: 'CI_003', status: 'NORMAL', checkedAt: tsAgo(1298000000), checkedBy: '张工' },
          { id: 'R_028', checkItemId: 'CI_004', status: 'NORMAL', checkedAt: tsAgo(1297000000), checkedBy: '张工' },
          { id: 'R_029', checkItemId: 'CI_006', status: 'ANOMALY', anomalyId: 'ANOM_006', checkedAt: tsAgo(1296000000), checkedBy: '张工' },
        ],
        anomalies: [
          {
            id: 'ANOM_006',
            inspectionOrderId: 'ORD_SAMPLE_008',
            checkItemId: 'CI_006',
            description: '模具固定螺丝松动',
            severity: 'HIGH',
            evidencePaths: [`/api/evidence/${SAMPLE_EVIDENCE_FILENAME}`],
            reportedBy: '张工',
            reportedAt: tsAgo(1296000000),
            resolvedAt: tsAgo(1270000000),
            resolvedBy: '李主管',
            resolution: '已重新紧固并加固',
          },
        ],
        operationLogs: [
          { id: 'LOG_021', inspectionOrderId: 'ORD_SAMPLE_008', action: 'CREATE', fromStatus: null, toStatus: 'DRAFT', operator: '张工', timestamp: tsAgo(1310000000) },
          { id: 'LOG_022', inspectionOrderId: 'ORD_SAMPLE_008', action: 'SUBMIT_WITH_ANOMALY', fromStatus: 'DRAFT', toStatus: 'PENDING_REVIEW', operator: '张工', timestamp: tsAgo(1295000000) },
          { id: 'LOG_023', inspectionOrderId: 'ORD_SAMPLE_008', action: 'REVIEW', fromStatus: 'PENDING_REVIEW', toStatus: 'REVIEWED', operator: '李主管', timestamp: tsAgo(1275000000) },
          { id: 'LOG_024', inspectionOrderId: 'ORD_SAMPLE_008', action: 'CLOSE', fromStatus: 'REVIEWED', toStatus: 'CLOSED', operator: '李主管', timestamp: tsAgo(1270000000) },
        ],
        startedAt: tsAgo(1310000000),
        submittedAt: tsAgo(1295000000),
        reviewedAt: tsAgo(1275000000),
        closedAt: tsAgo(1270000000),
        createdAt: tsAgo(1310000000),
        updatedAt: tsAgo(1270000000),
      },
      {
        id: 'ORD_SAMPLE_009',
        planId: 'PLAN_001',
        deviceId: 'DEV_001',
        shiftId: 'SHFT_001',
        shiftDate: daysAgo(20),
        status: 'CLOSED',
        operator: '张工',
        supervisor: '李主管',
        results: [
          { id: 'R_030', checkItemId: 'CI_001', status: 'NORMAL', checkedAt: tsAgo(1700000000), checkedBy: '张工' },
          { id: 'R_031', checkItemId: 'CI_002', status: 'NORMAL', checkedAt: tsAgo(1699000000), checkedBy: '张工' },
          { id: 'R_032', checkItemId: 'CI_003', status: 'NORMAL', checkedAt: tsAgo(1698000000), checkedBy: '张工' },
          { id: 'R_033', checkItemId: 'CI_004', status: 'NORMAL', checkedAt: tsAgo(1697000000), checkedBy: '张工' },
          { id: 'R_034', checkItemId: 'CI_005', status: 'NORMAL', checkedAt: tsAgo(1696000000), checkedBy: '张工' },
        ],
        anomalies: [],
        operationLogs: [
          { id: 'LOG_025', inspectionOrderId: 'ORD_SAMPLE_009', action: 'CREATE', fromStatus: null, toStatus: 'DRAFT', operator: '张工', timestamp: tsAgo(1710000000) },
          { id: 'LOG_026', inspectionOrderId: 'ORD_SAMPLE_009', action: 'SUBMIT', fromStatus: 'DRAFT', toStatus: 'COMPLETED', operator: '张工', timestamp: tsAgo(1695000000) },
          { id: 'LOG_027', inspectionOrderId: 'ORD_SAMPLE_009', action: 'REVIEW', fromStatus: 'COMPLETED', toStatus: 'REVIEWED', operator: '李主管', timestamp: tsAgo(1680000000) },
          { id: 'LOG_028', inspectionOrderId: 'ORD_SAMPLE_009', action: 'CLOSE', fromStatus: 'REVIEWED', toStatus: 'CLOSED', operator: '李主管', timestamp: tsAgo(1675000000) },
        ],
        startedAt: tsAgo(1710000000),
        submittedAt: tsAgo(1695000000),
        reviewedAt: tsAgo(1680000000),
        closedAt: tsAgo(1675000000),
        createdAt: tsAgo(1710000000),
        updatedAt: tsAgo(1675000000),
      },
      {
        id: 'ORD_SAMPLE_010',
        planId: 'PLAN_002',
        deviceId: 'DEV_002',
        shiftId: 'SHFT_002',
        shiftDate: daysAgo(20),
        status: 'CLOSED',
        operator: '王工',
        supervisor: '李主管',
        results: [
          { id: 'R_035', checkItemId: 'CI_001', status: 'NORMAL', checkedAt: tsAgo(1700000000), checkedBy: '王工' },
          { id: 'R_036', checkItemId: 'CI_002', status: 'ANOMALY', anomalyId: 'ANOM_007', checkedAt: tsAgo(1699000000), checkedBy: '王工' },
          { id: 'R_037', checkItemId: 'CI_003', status: 'NORMAL', checkedAt: tsAgo(1698000000), checkedBy: '王工' },
          { id: 'R_038', checkItemId: 'CI_004', status: 'NORMAL', checkedAt: tsAgo(1697000000), checkedBy: '王工' },
          { id: 'R_039', checkItemId: 'CI_006', status: 'NORMAL', checkedAt: tsAgo(1696000000), checkedBy: '王工' },
        ],
        anomalies: [
          {
            id: 'ANOM_007',
            inspectionOrderId: 'ORD_SAMPLE_010',
            checkItemId: 'CI_002',
            description: '润滑油颜色偏黄，可能需要更换',
            severity: 'LOW',
            evidencePaths: [`/api/evidence/${SAMPLE_EVIDENCE_FILENAME}`],
            reportedBy: '王工',
            reportedAt: tsAgo(1699000000),
            resolvedAt: tsAgo(1675000000),
            resolvedBy: '李主管',
            resolution: '已安排下周换油',
          },
        ],
        operationLogs: [
          { id: 'LOG_029', inspectionOrderId: 'ORD_SAMPLE_010', action: 'CREATE', fromStatus: null, toStatus: 'DRAFT', operator: '王工', timestamp: tsAgo(1710000000) },
          { id: 'LOG_030', inspectionOrderId: 'ORD_SAMPLE_010', action: 'SUBMIT_WITH_ANOMALY', fromStatus: 'DRAFT', toStatus: 'PENDING_REVIEW', operator: '王工', timestamp: tsAgo(1695000000) },
          { id: 'LOG_031', inspectionOrderId: 'ORD_SAMPLE_010', action: 'REVIEW', fromStatus: 'PENDING_REVIEW', toStatus: 'REVIEWED', operator: '李主管', timestamp: tsAgo(1680000000) },
          { id: 'LOG_032', inspectionOrderId: 'ORD_SAMPLE_010', action: 'CLOSE', fromStatus: 'REVIEWED', toStatus: 'CLOSED', operator: '李主管', timestamp: tsAgo(1675000000) },
        ],
        startedAt: tsAgo(1710000000),
        submittedAt: tsAgo(1695000000),
        reviewedAt: tsAgo(1680000000),
        closedAt: tsAgo(1675000000),
        createdAt: tsAgo(1710000000),
        updatedAt: tsAgo(1675000000),
      },
      {
        id: 'ORD_SAMPLE_011',
        planId: 'PLAN_003',
        deviceId: 'DEV_003',
        shiftId: 'SHFT_002',
        shiftDate: daysAgo(20),
        status: 'CLOSED',
        operator: '赵工',
        supervisor: '李主管',
        results: [
          { id: 'R_040', checkItemId: 'CI_001', status: 'NORMAL', checkedAt: tsAgo(1700000000), checkedBy: '赵工' },
          { id: 'R_041', checkItemId: 'CI_002', status: 'NORMAL', checkedAt: tsAgo(1699000000), checkedBy: '赵工' },
          { id: 'R_042', checkItemId: 'CI_004', status: 'NORMAL', checkedAt: tsAgo(1698000000), checkedBy: '赵工' },
          { id: 'R_043', checkItemId: 'CI_006', status: 'ANOMALY', anomalyId: 'ANOM_008', checkedAt: tsAgo(1697000000), checkedBy: '赵工' },
        ],
        anomalies: [
          {
            id: 'ANOM_008',
            inspectionOrderId: 'ORD_SAMPLE_011',
            checkItemId: 'CI_006',
            description: '模具表面有轻微划痕',
            severity: 'MEDIUM',
            evidencePaths: [`/api/evidence/${SAMPLE_EVIDENCE_FILENAME}`],
            reportedBy: '赵工',
            reportedAt: tsAgo(1697000000),
            resolvedAt: tsAgo(1675000000),
            resolvedBy: '李主管',
            resolution: '已打磨修复',
          },
        ],
        operationLogs: [
          { id: 'LOG_033', inspectionOrderId: 'ORD_SAMPLE_011', action: 'CREATE', fromStatus: null, toStatus: 'DRAFT', operator: '赵工', timestamp: tsAgo(1710000000) },
          { id: 'LOG_034', inspectionOrderId: 'ORD_SAMPLE_011', action: 'SUBMIT_WITH_ANOMALY', fromStatus: 'DRAFT', toStatus: 'PENDING_REVIEW', operator: '赵工', timestamp: tsAgo(1695000000) },
          { id: 'LOG_035', inspectionOrderId: 'ORD_SAMPLE_011', action: 'REVIEW', fromStatus: 'PENDING_REVIEW', toStatus: 'REVIEWED', operator: '李主管', timestamp: tsAgo(1680000000) },
          { id: 'LOG_036', inspectionOrderId: 'ORD_SAMPLE_011', action: 'CLOSE', fromStatus: 'REVIEWED', toStatus: 'CLOSED', operator: '李主管', timestamp: tsAgo(1675000000) },
        ],
        startedAt: tsAgo(1710000000),
        submittedAt: tsAgo(1695000000),
        reviewedAt: tsAgo(1680000000),
        closedAt: tsAgo(1675000000),
        createdAt: tsAgo(1710000000),
        updatedAt: tsAgo(1675000000),
      },
      {
        id: 'ORD_SAMPLE_012',
        planId: 'PLAN_005',
        deviceId: 'DEV_001',
        shiftId: 'SHFT_003',
        shiftDate: daysAgo(25),
        status: 'CLOSED',
        operator: '王工',
        supervisor: '李主管',
        results: [
          { id: 'R_044', checkItemId: 'CI_001', status: 'NORMAL', checkedAt: tsAgo(2100000000), checkedBy: '王工' },
          { id: 'R_045', checkItemId: 'CI_002', status: 'NORMAL', checkedAt: tsAgo(2099000000), checkedBy: '王工' },
          { id: 'R_046', checkItemId: 'CI_003', status: 'NORMAL', checkedAt: tsAgo(2098000000), checkedBy: '王工' },
          { id: 'R_047', checkItemId: 'CI_004', status: 'NORMAL', checkedAt: tsAgo(2097000000), checkedBy: '王工' },
          { id: 'R_048', checkItemId: 'CI_005', status: 'ANOMALY', anomalyId: 'ANOM_009', checkedAt: tsAgo(2096000000), checkedBy: '王工' },
        ],
        anomalies: [
          {
            id: 'ANOM_009',
            inspectionOrderId: 'ORD_SAMPLE_012',
            checkItemId: 'CI_005',
            description: '冷却液有泄漏痕迹',
            severity: 'HIGH',
            evidencePaths: [`/api/evidence/${SAMPLE_EVIDENCE_FILENAME}`],
            reportedBy: '王工',
            reportedAt: tsAgo(2096000000),
            resolvedAt: tsAgo(2070000000),
            resolvedBy: '李主管',
            resolution: '更换冷却液管路',
          },
        ],
        operationLogs: [
          { id: 'LOG_037', inspectionOrderId: 'ORD_SAMPLE_012', action: 'CREATE', fromStatus: null, toStatus: 'DRAFT', operator: '王工', timestamp: tsAgo(2110000000) },
          { id: 'LOG_038', inspectionOrderId: 'ORD_SAMPLE_012', action: 'SUBMIT_WITH_ANOMALY', fromStatus: 'DRAFT', toStatus: 'PENDING_REVIEW', operator: '王工', timestamp: tsAgo(2095000000) },
          { id: 'LOG_039', inspectionOrderId: 'ORD_SAMPLE_012', action: 'REVIEW', fromStatus: 'PENDING_REVIEW', toStatus: 'REVIEWED', operator: '李主管', timestamp: tsAgo(2080000000) },
          { id: 'LOG_040', inspectionOrderId: 'ORD_SAMPLE_012', action: 'CLOSE', fromStatus: 'REVIEWED', toStatus: 'CLOSED', operator: '李主管', timestamp: tsAgo(2070000000) },
        ],
        startedAt: tsAgo(2110000000),
        submittedAt: tsAgo(2095000000),
        reviewedAt: tsAgo(2080000000),
        closedAt: tsAgo(2070000000),
        createdAt: tsAgo(2110000000),
        updatedAt: tsAgo(2070000000),
      },
      {
        id: 'ORD_SAMPLE_013',
        planId: 'PLAN_001',
        deviceId: 'DEV_001',
        shiftId: 'SHFT_001',
        shiftDate: daysAgo(8),
        status: 'CLOSED',
        operator: '张工',
        supervisor: '李主管',
        results: [
          { id: 'R_049', checkItemId: 'CI_001', status: 'NORMAL', checkedAt: tsAgo(700000000), checkedBy: '张工' },
          { id: 'R_050', checkItemId: 'CI_002', status: 'NORMAL', checkedAt: tsAgo(699000000), checkedBy: '张工' },
          { id: 'R_051', checkItemId: 'CI_003', status: 'ANOMALY', anomalyId: 'ANOM_010', checkedAt: tsAgo(698000000), checkedBy: '张工' },
          { id: 'R_052', checkItemId: 'CI_004', status: 'NORMAL', checkedAt: tsAgo(697000000), checkedBy: '张工' },
          { id: 'R_053', checkItemId: 'CI_005', status: 'NORMAL', checkedAt: tsAgo(696000000), checkedBy: '张工' },
        ],
        anomalies: [
          {
            id: 'ANOM_010',
            inspectionOrderId: 'ORD_SAMPLE_013',
            checkItemId: 'CI_003',
            description: '气压偏低，约0.45MPa',
            severity: 'MEDIUM',
            evidencePaths: [`/api/evidence/${SAMPLE_EVIDENCE_FILENAME}`],
            reportedBy: '张工',
            reportedAt: tsAgo(698000000),
            resolvedAt: tsAgo(670000000),
            resolvedBy: '李主管',
            resolution: '已调节气压阀',
          },
        ],
        operationLogs: [
          { id: 'LOG_041', inspectionOrderId: 'ORD_SAMPLE_013', action: 'CREATE', fromStatus: null, toStatus: 'DRAFT', operator: '张工', timestamp: tsAgo(710000000) },
          { id: 'LOG_042', inspectionOrderId: 'ORD_SAMPLE_013', action: 'SUBMIT_WITH_ANOMALY', fromStatus: 'DRAFT', toStatus: 'PENDING_REVIEW', operator: '张工', timestamp: tsAgo(695000000) },
          { id: 'LOG_043', inspectionOrderId: 'ORD_SAMPLE_013', action: 'REVIEW', fromStatus: 'PENDING_REVIEW', toStatus: 'REVIEWED', operator: '李主管', timestamp: tsAgo(680000000) },
          { id: 'LOG_044', inspectionOrderId: 'ORD_SAMPLE_013', action: 'CLOSE', fromStatus: 'REVIEWED', toStatus: 'CLOSED', operator: '李主管', timestamp: tsAgo(670000000) },
        ],
        startedAt: tsAgo(710000000),
        submittedAt: tsAgo(695000000),
        reviewedAt: tsAgo(680000000),
        closedAt: tsAgo(670000000),
        createdAt: tsAgo(710000000),
        updatedAt: tsAgo(670000000),
      },
      {
        id: 'ORD_SAMPLE_014',
        planId: 'PLAN_002',
        deviceId: 'DEV_002',
        shiftId: 'SHFT_001',
        shiftDate: daysAgo(8),
        status: 'CLOSED',
        operator: '王工',
        supervisor: '李主管',
        results: [
          { id: 'R_054', checkItemId: 'CI_001', status: 'NORMAL', checkedAt: tsAgo(700000000), checkedBy: '王工' },
          { id: 'R_055', checkItemId: 'CI_002', status: 'NORMAL', checkedAt: tsAgo(699000000), checkedBy: '王工' },
          { id: 'R_056', checkItemId: 'CI_003', status: 'NORMAL', checkedAt: tsAgo(698000000), checkedBy: '王工' },
          { id: 'R_057', checkItemId: 'CI_004', status: 'NORMAL', checkedAt: tsAgo(697000000), checkedBy: '王工' },
          { id: 'R_058', checkItemId: 'CI_006', status: 'NORMAL', checkedAt: tsAgo(696000000), checkedBy: '王工' },
        ],
        anomalies: [],
        operationLogs: [
          { id: 'LOG_045', inspectionOrderId: 'ORD_SAMPLE_014', action: 'CREATE', fromStatus: null, toStatus: 'DRAFT', operator: '王工', timestamp: tsAgo(710000000) },
          { id: 'LOG_046', inspectionOrderId: 'ORD_SAMPLE_014', action: 'SUBMIT', fromStatus: 'DRAFT', toStatus: 'COMPLETED', operator: '王工', timestamp: tsAgo(695000000) },
          { id: 'LOG_047', inspectionOrderId: 'ORD_SAMPLE_014', action: 'REVIEW', fromStatus: 'COMPLETED', toStatus: 'REVIEWED', operator: '李主管', timestamp: tsAgo(680000000) },
          { id: 'LOG_048', inspectionOrderId: 'ORD_SAMPLE_014', action: 'CLOSE', fromStatus: 'REVIEWED', toStatus: 'CLOSED', operator: '李主管', timestamp: tsAgo(670000000) },
        ],
        startedAt: tsAgo(710000000),
        submittedAt: tsAgo(695000000),
        reviewedAt: tsAgo(680000000),
        closedAt: tsAgo(670000000),
        createdAt: tsAgo(710000000),
        updatedAt: tsAgo(670000000),
      },
      {
        id: 'ORD_SAMPLE_015',
        planId: 'PLAN_003',
        deviceId: 'DEV_003',
        shiftId: 'SHFT_002',
        shiftDate: daysAgo(12),
        status: 'CLOSED',
        operator: '张工',
        supervisor: '李主管',
        results: [
          { id: 'R_059', checkItemId: 'CI_001', status: 'NORMAL', checkedAt: tsAgo(1000000000), checkedBy: '张工' },
          { id: 'R_060', checkItemId: 'CI_002', status: 'ANOMALY', anomalyId: 'ANOM_011', checkedAt: tsAgo(999000000), checkedBy: '张工' },
          { id: 'R_061', checkItemId: 'CI_004', status: 'NORMAL', checkedAt: tsAgo(998000000), checkedBy: '张工' },
          { id: 'R_062', checkItemId: 'CI_006', status: 'NORMAL', checkedAt: tsAgo(997000000), checkedBy: '张工' },
        ],
        anomalies: [
          {
            id: 'ANOM_011',
            inspectionOrderId: 'ORD_SAMPLE_015',
            checkItemId: 'CI_002',
            description: '润滑油位略低',
            severity: 'LOW',
            evidencePaths: [`/api/evidence/${SAMPLE_EVIDENCE_FILENAME}`],
            reportedBy: '张工',
            reportedAt: tsAgo(999000000),
            resolvedAt: tsAgo(970000000),
            resolvedBy: '李主管',
            resolution: '已补油',
          },
        ],
        operationLogs: [
          { id: 'LOG_049', inspectionOrderId: 'ORD_SAMPLE_015', action: 'CREATE', fromStatus: null, toStatus: 'DRAFT', operator: '张工', timestamp: tsAgo(1010000000) },
          { id: 'LOG_050', inspectionOrderId: 'ORD_SAMPLE_015', action: 'SUBMIT_WITH_ANOMALY', fromStatus: 'DRAFT', toStatus: 'PENDING_REVIEW', operator: '张工', timestamp: tsAgo(995000000) },
          { id: 'LOG_051', inspectionOrderId: 'ORD_SAMPLE_015', action: 'REVIEW', fromStatus: 'PENDING_REVIEW', toStatus: 'REVIEWED', operator: '李主管', timestamp: tsAgo(980000000) },
          { id: 'LOG_052', inspectionOrderId: 'ORD_SAMPLE_015', action: 'CLOSE', fromStatus: 'REVIEWED', toStatus: 'CLOSED', operator: '李主管', timestamp: tsAgo(970000000) },
        ],
        startedAt: tsAgo(1010000000),
        submittedAt: tsAgo(995000000),
        reviewedAt: tsAgo(980000000),
        closedAt: tsAgo(970000000),
        createdAt: tsAgo(1010000000),
        updatedAt: tsAgo(970000000),
      },
      {
        id: 'ORD_SAMPLE_016',
        planId: 'PLAN_004',
        deviceId: 'DEV_002',
        shiftId: 'SHFT_002',
        shiftDate: daysAgo(18),
        status: 'COMPLETED',
        operator: '赵工',
        results: [
          { id: 'R_063', checkItemId: 'CI_001', status: 'NORMAL', checkedAt: tsAgo(1500000000), checkedBy: '赵工' },
          { id: 'R_064', checkItemId: 'CI_002', status: 'NORMAL', checkedAt: tsAgo(1499000000), checkedBy: '赵工' },
          { id: 'R_065', checkItemId: 'CI_003', status: 'NORMAL', checkedAt: tsAgo(1498000000), checkedBy: '赵工' },
          { id: 'R_066', checkItemId: 'CI_004', status: 'NORMAL', checkedAt: tsAgo(1497000000), checkedBy: '赵工' },
          { id: 'R_067', checkItemId: 'CI_006', status: 'NORMAL', checkedAt: tsAgo(1496000000), checkedBy: '赵工' },
        ],
        anomalies: [],
        operationLogs: [
          { id: 'LOG_053', inspectionOrderId: 'ORD_SAMPLE_016', action: 'CREATE', fromStatus: null, toStatus: 'DRAFT', operator: '赵工', timestamp: tsAgo(1510000000) },
          { id: 'LOG_054', inspectionOrderId: 'ORD_SAMPLE_016', action: 'SUBMIT', fromStatus: 'DRAFT', toStatus: 'COMPLETED', operator: '赵工', timestamp: tsAgo(1495000000) },
        ],
        startedAt: tsAgo(1510000000),
        submittedAt: tsAgo(1495000000),
        createdAt: tsAgo(1510000000),
        updatedAt: tsAgo(1495000000),
      },
    ],
    statsLogs: [],
    maintenanceReminders: [],
    maintenanceImportLogs: [],
    handoverRecords: [],
    handoverImportLogs: [],
  }
}
