import type { Database } from '../types/index.js'

export function getInitialData(): Database {
  const now = new Date().toISOString()
  const today = new Date().toISOString().slice(0, 10)
  const yesterday = new Date(Date.now() - 86400000).toISOString().slice(0, 10)

  return {
    devices: [
      {
        id: 'DEV_001',
        name: 'CNC加工中心 A-1',
        code: 'CNC-A1',
        location: '一号车间 3号位',
        description: '五轴联动数控加工中心',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'DEV_002',
        name: '注塑机 B-2',
        code: 'INJ-B2',
        location: '二号车间 1号位',
        description: '320吨伺服注塑机',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'DEV_003',
        name: '冲压机 C-3',
        code: 'PRS-C3',
        location: '一号车间 7号位',
        description: '400吨高速冲床',
        createdAt: now,
        updatedAt: now,
      },
    ],
    shifts: [
      {
        id: 'SHFT_001',
        name: '早班',
        type: 'MORNING',
        startTime: '08:00',
        endTime: '16:00',
        description: '白班第一班',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'SHFT_002',
        name: '中班',
        type: 'AFTERNOON',
        startTime: '16:00',
        endTime: '00:00',
        description: '白班第二班',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'SHFT_003',
        name: '夜班',
        type: 'NIGHT',
        startTime: '00:00',
        endTime: '08:00',
        description: '夜班',
        createdAt: now,
        updatedAt: now,
      },
    ],
    checkItems: [
      {
        id: 'CI_001',
        name: '设备外观检查',
        code: 'VIS-001',
        category: '目视检查',
        description: '检查设备外观是否完好，无破损、无变形',
        standard: '设备外观整洁，无明显磕碰、变形、锈蚀',
        deviceIds: ['DEV_001', 'DEV_002', 'DEV_003'],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'CI_002',
        name: '润滑油位',
        code: 'OIL-001',
        category: '润滑系统',
        description: '检查各润滑点油位是否正常',
        standard: '油位在上下刻度线之间，无渗漏',
        deviceIds: ['DEV_001', 'DEV_002', 'DEV_003'],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'CI_003',
        name: '气压系统',
        code: 'AIR-001',
        category: '气动系统',
        description: '检查气源压力和管路',
        standard: '气压 0.5~0.7MPa，管路无泄漏',
        deviceIds: ['DEV_001', 'DEV_002'],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'CI_004',
        name: '安全门开关',
        code: 'SAF-001',
        category: '安全装置',
        description: '检查安全门联锁功能',
        standard: '安全门打开时设备立即停止运行',
        deviceIds: ['DEV_001', 'DEV_002', 'DEV_003'],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'CI_005',
        name: '冷却系统',
        code: 'CLN-001',
        category: '温控系统',
        description: '检查冷却液循环和温度',
        standard: '冷却液充足，温度 20~28°C',
        deviceIds: ['DEV_001'],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'CI_006',
        name: '模具安装',
        code: 'MOL-001',
        category: '工装模具',
        description: '检查模具安装固定情况',
        standard: '模具安装牢固，定位准确',
        deviceIds: ['DEV_002', 'DEV_003'],
        createdAt: now,
        updatedAt: now,
      },
    ],
    inspectionPlans: [
      {
        id: 'PLAN_001',
        name: 'CNC-A1 日常点检',
        deviceId: 'DEV_001',
        shiftId: 'SHFT_001',
        checkItemIds: ['CI_001', 'CI_002', 'CI_003', 'CI_004', 'CI_005'],
        frequency: '每日每班次',
        description: 'CNC加工中心A-1每班开机前点检',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'PLAN_002',
        name: 'INJ-B2 日常点检',
        deviceId: 'DEV_002',
        shiftId: 'SHFT_001',
        checkItemIds: ['CI_001', 'CI_002', 'CI_003', 'CI_004', 'CI_006'],
        frequency: '每日每班次',
        description: '注塑机B-2每班开机前点检',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'PLAN_003',
        name: 'PRS-C3 日常点检',
        deviceId: 'DEV_003',
        shiftId: 'SHFT_002',
        checkItemIds: ['CI_001', 'CI_002', 'CI_004', 'CI_006'],
        frequency: '每日每班次',
        description: '冲压机C-3每班开机前点检',
        createdAt: now,
        updatedAt: now,
      },
    ],
    inspectionOrders: [
      {
        id: 'ORD_SAMPLE_001',
        planId: 'PLAN_001',
        deviceId: 'DEV_001',
        shiftId: 'SHFT_001',
        shiftDate: yesterday,
        status: 'CLOSED',
        operator: '张工',
        supervisor: '李主管',
        results: [
          {
            id: 'R_001',
            checkItemId: 'CI_001',
            status: 'NORMAL',
            checkedAt: new Date(Date.now() - 90000000).toISOString(),
            checkedBy: '张工',
          },
          {
            id: 'R_002',
            checkItemId: 'CI_002',
            status: 'NORMAL',
            checkedAt: new Date(Date.now() - 89000000).toISOString(),
            checkedBy: '张工',
          },
          {
            id: 'R_003',
            checkItemId: 'CI_003',
            status: 'NORMAL',
            checkedAt: new Date(Date.now() - 88000000).toISOString(),
            checkedBy: '张工',
          },
        ],
        anomalies: [],
        operationLogs: [
          {
            id: 'LOG_001',
            inspectionOrderId: 'ORD_SAMPLE_001',
            action: 'CREATE',
            fromStatus: null,
            toStatus: 'DRAFT',
            operator: '张工',
            timestamp: new Date(Date.now() - 100000000).toISOString(),
          },
          {
            id: 'LOG_002',
            inspectionOrderId: 'ORD_SAMPLE_001',
            action: 'SUBMIT',
            fromStatus: 'DRAFT',
            toStatus: 'COMPLETED',
            operator: '张工',
            timestamp: new Date(Date.now() - 80000000).toISOString(),
          },
          {
            id: 'LOG_003',
            inspectionOrderId: 'ORD_SAMPLE_001',
            action: 'CLOSE',
            fromStatus: 'REVIEWED',
            toStatus: 'CLOSED',
            operator: '李主管',
            timestamp: new Date(Date.now() - 40000000).toISOString(),
          },
        ],
        startedAt: new Date(Date.now() - 100000000).toISOString(),
        submittedAt: new Date(Date.now() - 80000000).toISOString(),
        reviewedAt: new Date(Date.now() - 50000000).toISOString(),
        closedAt: new Date(Date.now() - 40000000).toISOString(),
        createdAt: new Date(Date.now() - 100000000).toISOString(),
        updatedAt: new Date(Date.now() - 40000000).toISOString(),
      },
      {
        id: 'ORD_SAMPLE_002',
        planId: 'PLAN_002',
        deviceId: 'DEV_002',
        shiftId: 'SHFT_001',
        shiftDate: today,
        status: 'PENDING_REVIEW',
        operator: '王工',
        results: [
          {
            id: 'R_004',
            checkItemId: 'CI_001',
            status: 'NORMAL',
            checkedAt: new Date(Date.now() - 600000).toISOString(),
            checkedBy: '王工',
          },
          {
            id: 'R_005',
            checkItemId: 'CI_002',
            status: 'ANOMALY',
            anomalyId: 'ANOM_001',
            remark: '润滑油位偏低',
            checkedAt: new Date(Date.now() - 500000).toISOString(),
            checkedBy: '王工',
          },
        ],
        anomalies: [
          {
            id: 'ANOM_001',
            inspectionOrderId: 'ORD_SAMPLE_002',
            checkItemId: 'CI_002',
            description: '润滑油位低于最低刻度线约2cm，暂未发现渗漏点',
            severity: 'MEDIUM',
            evidencePaths: [],
            reportedBy: '王工',
            reportedAt: new Date(Date.now() - 500000).toISOString(),
          },
        ],
        operationLogs: [
          {
            id: 'LOG_004',
            inspectionOrderId: 'ORD_SAMPLE_002',
            action: 'CREATE',
            fromStatus: null,
            toStatus: 'DRAFT',
            operator: '王工',
            timestamp: new Date(Date.now() - 1200000).toISOString(),
          },
          {
            id: 'LOG_005',
            inspectionOrderId: 'ORD_SAMPLE_002',
            action: 'SUBMIT_WITH_ANOMALY',
            fromStatus: 'DRAFT',
            toStatus: 'PENDING_REVIEW',
            operator: '王工',
            timestamp: new Date(Date.now() - 400000).toISOString(),
          },
        ],
        startedAt: new Date(Date.now() - 1200000).toISOString(),
        submittedAt: new Date(Date.now() - 400000).toISOString(),
        createdAt: new Date(Date.now() - 1200000).toISOString(),
        updatedAt: new Date(Date.now() - 400000).toISOString(),
      },
    ],
  }
}
